# Generated by Django 3.2 on 2021-04-08 20:07

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='file',
            field=models.FileField(default='null', upload_to=games.models.game_file_name),
            preserve_default=False,
        ),
    ]
